### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by modgames44** [andy-man/ps4-wee-tools#1]
hello, the program crashes when trying to parse a nor dump, but with a syscon dump it works fine

**Comment by andy-man** [comment]
Provide link to your dump, which leads to errors, I'll check it out (you can post it here or pm me on [twitter](https://twitter.com/AndyManDev))

**Comment by modgames44** [comment]
> 

I just followed you on Twitter I will send you the link now on twitter of the dump of the nor. I am modgames44
