### ISSUE TITLE
Line 337 of tools.py references to f and x is correct.

### ISSUE THREAD

**Issue by MSXCelulares** [andy-man/ps4-wee-tools#13]
https://github.com/andy-man/ps4-wee-tools/blob/42ce6ea58e860a575f826c5338f1230b01efb2a8/tools/Tools.py#L337C113-L337C113

Hello dear, congratulations for your job. I very liked, but findly a issue and try fix. Thank so much.

Change line 337 of tools.py to:

file_list = [os.path.join(path, x) for x in os.listdir(path) if not os.path.isdir(os.path.join(path, x)) and x.lower().endswith('.bin')]

**Comment by andy-man** [comment]
thanks, will be fixed in the next commit
