### ISSUE TITLE
Reference f.lower().endswith('.bin') in line 337 of file tools.py

### ISSUE THREAD

**Issue by MSXCelulares** [andy-man/ps4-wee-tools#15]
https://github.com/andy-man/ps4-wee-tools/blob/42ce6ea58e860a575f826c5338f1230b01efb2a8/tools/Tools.py#L337

Hello Sir, sorry for my bad English, but I really liked your work and I would like to help you with some small corrections or suggestions as far as possible. I have a Technical Assistance and I am currently using your project, and over time I could collect data from new boards for future updates.
I humbly advise that on line 337 of the tools.py file there is a wrong reference to a variable "f" that was copied from another command line and I corrected it here to "x" and it worked perfectly. It also includes some improvements to the "c" Compare bin files... function, how can I send you a modified tools.py file so you can test it yourself?

**Comment by MSXCelulares** [comment]
This is a origin code image:
![compare_orig](https://github.com/andy-man/ps4-wee-tools/assets/96247543/e376446b-8432-4662-97b1-fe7540493b96)

this is a modify code image:
![new_compare_mod](https://github.com/andy-man/ps4-wee-tools/assets/96247543/434cfedc-bafd-4091-ae00-9c0e415916fb)

**Comment by MSXCelulares** [comment]
Sorry sir, I just now saw that you had already checked my previous question, I'm a noob at GITHUB so I ended up duplicating the ref post. to the error found, and only now I realized that I can post the file here.
[Tools.zip](https://github.com/andy-man/ps4-wee-tools/files/12665648/Tools.zip)

**Comment by andy-man** [comment]
Thanks for your suggestions, I've already made some corrections according to your feedback.
I don't intend to include entropy check into current compare function (for performance reasons), however you you can fork main repo and make you own version.
