### ISSUE TITLE
Corrupted Syscon Backup

### ISSUE THREAD

**Issue by tttheslimshadyyy** [andy-man/ps4-wee-tools#18]
Hello friend.
Thank you for your excellent work.
I used abkarino method to dump syscon but i consider it as a bad reading.
Everything was fine, the resistor, and i was dump dumping off the board even the connections was solid.
now after enabling the debug mode on syscon i got blue light on ps4 and the uart reading is:
ERROR: getManufacturingMode(1627) sceB1SnvsRecvSector -36
ERROR: main(3728) getManufacturingMode -36
I tried cleaning and rebuilding snvs but nothing worked :(

**Comment by andy-man** [comment]
You could try to use another working syscon dump (with same fw) and then flash your snvs/nvs
