### ISSUE TITLE
Patching syscon problem

### ISSUE THREAD

**Issue by hardboy89** [andy-man/ps4-wee-tools#19]
I have a problem, when i use auto snvs and i select the recommended method it wont create the patched syscon. the program automatically jumps back to the syscon dump info. I tried with another computer but its the same. The status remains probably patchable. I use windows 10. Thank you

**Comment by andy-man** [comment]
give more details:
-version of wee tools
-exe or py script
-provide your dump file

**Comment by hardboy89** [comment]
I used 0.8.5 and after that 0.8.7, still the same. I followed modded warfare tutorial video and there i noticed that when he patch the syscon the patched syscon message appears on hes program. I uploaded the syscon [https://mega.nz/file/cbYkETST#S13kQJ2dHUaJoFHSqOCSgfPYCL5vVz3ilGsk2XbI1cQ](url) I uploaded a private video on youtube to show you the problem [https://www.youtube.com/watch?v=q0y4w-e4yDg](url)

Thank you

**Comment by andy-man** [comment]
There is no problem with syscon dump neither tool. You should input "2" and not "b" - be more attentive next time.
