### ISSUE TITLE
Does the version check in NOR tell the other version present in the coreos header?

### ISSUE THREAD

**Issue by galacticwarrior448** [andy-man/ps4-wee-tools#2]
Hello, this is a small question but, in the VERS field in the NOR patcher, does it show the other firmware verison installed? Because it shows 10.50 | 10.50 for me. I had accidentally updated to 10.50 and immediately powered off my console right afterwards, so there should have been no way that the the backup would have gotten lost or overwritten. The syscon part shows my dump as probably patchable, and the last two 08 0b structures are different so I was wondering if the NOR part is accurate or not.

**Comment by andy-man** [comment]
Currently it has a bug in FW version detection in different slots. Will be fixed soon. But only for Slim/Pro and 12xx Fat. 
I still dunno where is 2nd FW info for 1xxx/11xx models

**Comment by galacticwarrior448** [comment]
Hello, I tried the newest version and it now shows 3.15 instead of 9.00. I have a 1206A ps4

**Comment by andy-man** [comment]
It is experemental feature and probably will be removed cause it is not correct according to user replies. I think it is not possible to detect  fw version for inactive slot in nor dump. Syscon probably has such info, but it's encrypted. There's too little info about
