### ISSUE TITLE
Wrong status "Already patched or stuck on update"

### ISSUE THREAD

**Issue by rutdarkronin** [andy-man/ps4-wee-tools#20]
Good day!
First of all, allow me to thank you from the bottom of my heart for your brilliant PS4 swiss knife tool as it has saved a lot of consoles out there!
One thing though, today I have managed to succesfully downgrade slim SAD-001 unit with your utility, but upon checking syscon it gave me a status "Already patched or stuck on update" giving me some hard time. But the thing is that I have switched slot with your utility (method 3) and autopatch SNVS (method C) and console boots just fine with 9.00 onboard.
I'm attaching the dumps so you could take a look just in case.
Once again, thank you!

[part1.zip](https://github.com/andy-man/ps4-wee-tools/files/12861991/part1.zip)
[part2.zip](https://github.com/andy-man/ps4-wee-tools/files/12861994/part2.zip)
You need to rename part2.zip to part1.z01 for files to be extracted due to github's file upload issues.

**Comment by andy-man** [comment]
Thank you for feedback, I know about this bug, it's already fixed in 0.9.0. Just wait for update it will be very soon.

**Comment by rutdarkronin** [comment]
Thank you for your reply!)
