### ISSUE TITLE
ModuleNotFoundError: No module named 'Crypto'

### ISSUE THREAD

**Issue by rasoulia** [andy-man/ps4-wee-tools#21]
hi. thanks for creating such a useful tools for free.
i want to run python version of you project and after i installed both dependencies it's say 
`ModuleNotFoundError: No module named 'Crypto'`

so after i search about it it's find out that we must drop crypto and use pycryptodome instead.
so after i installed pycryptodome. program run fin but don't know functionality it's same or not. since you say install crypto but i installed pycryptodome.

so what should i do.
since you not released exe version of your product. i share it in here if functionality it's fine:

> only use this when author approve it : https://mega.nz/file/L9hmgYaD#lsm-A8tccB-mNDcKZcXestsbT-k4UMRQybxNlfwxDDU

**Comment by andy-man** [comment]
Yes you are right `pycryptodome` is correct one. It's my mistake, I'll update the readme in next commit
