### ISSUE TITLE
SPIWay Diagram Mistakes

### ISSUE THREAD

**Issue by ng1n33r** [andy-man/ps4-wee-tools#22]
Hi,

The “Convert 5v to 2.8-3.3v” section in the middle of the "..\ps4-wee-tools-v0.9.x\assets\hw\spiway\diagram.jpg" diagram for the Teensy++ 2.0 NOR connections has a couple of mistakes:

- **Variant A**
  - VCC and GND wires/lines should be swapped
  - With the above correction, the shown R1 & R2 configuration would give 3.96V and not 2.8V-3.3V
- **Variant B**
  - 3v3 VCC should be the center pin (2, Vout for AMS1117 ) on the left (currently NC)

Applicable to versions v0.9.0 and v0.9.5.

Nevertheless, this is a great tool. Looking forward to more features.

Cheers

**Comment by andy-man** [comment]
There is no mistake, and your variants will also work
 Variant A: if you mean just to swap VCC label with GND label (on photo) the voltage remains the same ~4V (without load)
 Variant B: yes you can use V-out on the left side (central pin2) - the right side is the same V-out like pin2 on left side

**Comment by ng1n33r** [comment]
Hi,

Variant A as it stands is doing absolutely nothing. 5V in, 5V out.

The variant A circuit as it stands will not provide 3.3V but 5V. NOR chips have a max input voltage of 3.6V. There is high risk the current variant A circuit will damage NOR chips (and/or other chips, if users perform this mod/install while the NOR chip is still on-board the PS4's main board, while not lifting the NOR's VCC pin (which is only possible for SOP16 NOR chips)).

For variant A: Currently the input 5V is the same wire/node (orange) as the output wire/node. The 5V is not going through any resistor(s) for a voltage drop to occur to be a voltage divider. Second, there's never any use of putting resistor(s) between two ground points.

In order for variant A to be a voltage divider, the input voltage 5V has to be going into top left, into the left of R1 (currently, incorrectly GND). And, the output 3.3V has to be connected to the top right, into the R1-R2 node (currently, incorrectly GND). And, for the whole bottom wire/node to be GND.

In order for variant A to be correct, and act as a voltage divider, the above changes must be done. Once done, the current values of R1 and R2 will give a Vout of 3.96V, which not only it's too high for a NOR chip, but it is not in the range of 2.8V-3.3V.

For variant B: Per the datasheet of AMS1117, Vout is pin 2 and only pin 2. The large/wide metal tab on the right, is used to solder/hold the component to the board. That large metal tab is sometimes a NC, but often it's GND.

I strongly suggest you verify the variant A and B circuits on a breadboard, or using a basic circuit simulator. If you are unable to verify them, I strongly suggest your remove those diagrams until confirmed.

Cheers.

**Comment by andy-man** [comment]
Could you draw you version of "variant A"? Maybe there is something that I miss in your text.
About AMS1117 - the right side (the single pin) is Vout (at least mine). However I'll add notes from you about pin2 to diagram.

**Comment by ng1n33r** [comment]
[Voltage Divider Calculator](https://www.xarg.org/tools/voltage-divider-calculator/)

**Comment by MSXCelulares** [comment]
Hello my friend, the Variant A is only names trails inverted of the GND with VCC was this image. The value of the resistors does not need to be modified as some USB ports that power the Teensy suffer a loss to 4.85v and not 5v. Now with Variant B, at least in my region of the world, all AMS1117 have the unified central pin, I never found a datasheet with a note about the solid plate being NC.
![271427233-1e54b38f-5471-462e-ac6c-db1aba837f79](https://github.com/andy-man/ps4-wee-tools/assets/96247543/b773988c-28d7-4ea8-9a22-87641bd44f73)

**Comment by ng1n33r** [comment]
Hi,

Even with a Vin of 4.85V, the above resistors (47Ω and 180Ω) would give a Vout of 3.85V. With those values, Vin would need to drop to 3.8V to get a Vout of 3.0V.

For the voltage regulator AMS1117, the tab is Vout _only_ for the TO-252 package. The diagram you have is for an AMS1117 TO-223  package.

It's up to you. Thanks for the great tool.

[AMS1117 Datasheet](http://www.advanced-monolithic.com/pdf/ds1117.pdf)

![Screenshot 2023-11-09 194624](https://github.com/andy-man/ps4-wee-tools/assets/150209837/6f61244e-9a76-43cf-a1b2-cf5b3ba7d78e)

Cheers

**Comment by MSXCelulares** [comment]
Hello sir ng1n33r, I'm not responsible for anything here, I'm just an enthusiast who is amazed by this tool ok, so with all due respect don't get me wrong, the fact that the TO-252 package designates tab as output is due to pin 2 being shortened in this type of package, this does not mean that in the SOT-223 package the Tab will be an NC pin, ok?
If you look at the data sheet, it also indicates the shortest rod in the TO-252 package as pin 2.

P.S.: Yes, the diagrams were tested in the laboratory and in practice they work.

I hope I helped with this tip and I'm glad you came to help, so this tool will develop faster and become increasingly reliable, may God enlighten our lives and that of our brother Andy-man. Thanks.
