### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by ArturSchnell** [andy-man/ps4-wee-tools#24]
When trying to write sflash0 back to the console, index out of range is thrown.

### SPIway:
  Version : 0.60
  Memory : 3942 bytes

### Chip configuration:
 Manufacturer / Device : 0xEF / 0x1940
 Brand : Winbond
 Chip type : W25Q256FV
 Chip size : 32 MB
 Sector size: 4096 bytes
 Block size: 65536 bytes
 Flash configuration: 4:1 | 16 | 512 | 8192

**Comment by ArturSchnell** [comment]
Hi, sorry for the missing data.
I used the ps4-wee-tools.exe v0.9.5 for this.

I selected the file itself in the SPIway screen, yes.
In the actions I selected "Write All" once. When the error was thrown, I also tried "Write Area". In both cases the same result 

It's best to just go through it step-by-step.

Default steps:
<img alt="main menu" src="https://github.com/andy-man/ps4-wee-tools/assets/100756263/c785ff51-137c-4a2e-a6bf-678157ab9d70" width="60%">
<img alt="serial ports" src="https://github.com/andy-man/ps4-wee-tools/assets/100756263/25ccf0e5-c592-45e4-98dc-c7667d63d193" width="60%">

Here I select the file in the SPIway screen:
<img alt="select file" src="https://github.com/andy-man/ps4-wee-tools/assets/100756263/7d2ca303-3bf6-477c-8745-72ffe68078bf" width="60%">
<img alt="selected file" src="https://github.com/andy-man/ps4-wee-tools/assets/100756263/9d34057d-bb5d-4e64-886c-8a1c4cdc06ce" width="60%">

After that I want to flash the selected file:
<img alt="flash file" src="https://github.com/andy-man/ps4-wee-tools/assets/100756263/c29d938d-a3e2-4689-aa81-3fc0177a750c" width="60%">
<img alt="serial port flash" src="https://github.com/andy-man/ps4-wee-tools/assets/100756263/4f0bf733-f923-4203-8f21-7927fa1f730d" width="60%">

As soon as I press enter on this screen, the error message appears. I think I saw a red font flicker very briefly before the screen refreshed.
<img alt="index out of range error" src="https://github.com/andy-man/ps4-wee-tools/assets/100756263/edf269a5-950c-48a1-b349-e6781d3ac131" width="60%">

I hope this helps with the diagnosis. Thank you very much

**Comment by andy-man** [comment]
I have repeated your steps with 0.9.5 exe file (win10) and have not found this error
Btw, you can drag&drop dump file to app and then choose "f"

**Comment by MSXCelulares** [comment]
Hello sir, this Desktop folder need special permissions and perhaps your user don't have admin permission, try uncompress this app in C: or D:, and execute ps4_wee_tool.exe as admin mode. Stay with God.

**Comment by ArturSchnell** [comment]
Thanks for the information about the operating system. It looks like the problem is related to Windows 11. There were no problems on my laptop with Windows 10. I also gave the file admin rights like @MSXCelulares (although I didn't have that in mind). Unfortunately this did not solve the problem.
