### ISSUE TITLE
Syscon status :overwritten coreos slot

### ISSUE THREAD

**Issue by Mladicbt** [andy-man/ps4-wee-tools#25]
So is this is not patchable syscon !? Because on the version 0.9.5 says SC: autopatch now works with any* 
![20240104_010202](https://github.com/andy-man/ps4-wee-tools/assets/153337956/30dea1c9-6e5e-48f3-83ab-9fe9461534c1)

**Comment by andy-man** [comment]
Almost zero chances of success
Yes 0.9.5 has patch D but it is the same as manual method described here https://github.com/andy-man/ps4-wee-tools/issues/17)

**Comment by Mladicbt** [comment]
Ok thanks for responding
