### ISSUE TITLE
Strange issue with 9.03 -> 9.00 downgrade attempt.

### ISSUE THREAD

**Issue by rutdarkronin** [andy-man/ps4-wee-tools#27]
Hello dear Andy-man!
I've got something strange going on here with attempt to patch NVS for slot reverse:
(Note that initially console had DCT[6] error which was solved with bank replacement, well nevermind)

`secure loader build: Nov 10 2021 05:19:57 (r10475:release_branches/release_09.030) [711MHz] AGESA: ThebePBDK W5C21 ERROR: DCT[6] is disabled`
Here you can see that FW was 9.03 initially. 

Reverted slot:
`secure loader build: Sep  1 2021 05:19:44 (r10468:release_branches/release_09.000) [711MHz] AGESA: ThebePBDK W5C21 ERROR: DCT[6] is disabled`
Good, CoreOs seems intact and legit. Moving on to repair mobo, also flashed syscon B - patched, only to catch...:

`secure loader build: Sep  1 2021 05:19:44 (r10468:release_branches/release_09.000) [711MHz] AGESA: ThebePBDK W5C21
standby 06510000 
ERROR: main(3738) checkUpdVersion 0x6720000 != 0x9008000
`
Whoa! 6.72 with 06510000 standby? Right above 90300000? That's something unseen. Trying other patches as well:
`secure loader build: Sep  1 2021 05:19:44 (r10468:release_branches/release_09.000) [711MHz]
 AGESA: ThebePBDK W5C21
ERROR: main(3738) checkUpdVersion 0x6720000 != 0x9008000`
Different though because standby 06510000 missed,

Reverted to original syscon dump:
`secure loader build: Sep  1 2021 05:19:44 (r10468:release_branches/release_09.000) [711MHz]
           AGESA: ThebePBDK       W5C21
                                             standby 09030000
                                                             ERROR: main(3738) checkUpdVersion 0xffffffff != 0x9008000`
... which is pretty much expected.

Is there some block confusion inside damn thing? Could you please have a look?

Also noted that Wee-Tools doesn't seem to recognize 9.03 properly and displays it as 1.62 which is obviously wrong.

!!!Please change z.01.zip to simple z.01 extension to be extracted properly. Thanks!!!
[syscon903.zip](https://github.com/andy-man/ps4-wee-tools/files/14138812/syscon903.zip)
[flash903-900.z01.zip](https://github.com/andy-man/ps4-wee-tools/files/14138839/flash903-900.z01.zip)
[flash903-900.zip](https://github.com/andy-man/ps4-wee-tools/files/14138840/flash903-900.zip)

**Comment by rutdarkronin** [comment]
Well, back with update and it's an interesting one as I had to delete whole 20 lines from active block (which counts 300 lines total after chop-shop) to boot console with 9.00.
Please take a look at my dumps, there might be some usefullness.

**Comment by andy-man** [comment]
Syscon contains all previous firmware updates so it is normal. The more 08-0B entries you clean the lowest fw signature will be used. I suppose this particular syscon dump had some issue like stuck on update or something similar.

Contact me at [4PDA](https://4pda.to/forum/index.php?act=qms&mid=1765649), need more details.

**Comment by woooow1** [comment]
@rutdarkronin, indeed, software 9.03 is recognized like 1.62. But for me conversion seems to work fine, without any problems! So, maybe dump has some issues!
