### ISSUE TITLE
Manual SNVS patch rewrites original dump without any warning.

### ISSUE THREAD

**Issue by rutdarkronin** [andy-man/ps4-wee-tools#28]
Just as title says, when user performs manual SNVS patch with chopping some lines from active block, original dump rewrites straight away meaning that you actually cannot undone changes unless you have a backup. Huge one I guess as it can lead to permabrick giving the general unawareness of this behavior.

**Comment by andy-man** [comment]
Yes manual patch is applying edits straight to the file.
I'll consider adding warning to this screen
