### ISSUE TITLE
Any FW downgrade suggestion.

### ISSUE THREAD

**Issue by rutdarkronin** [andy-man/ps4-wee-tools#29]
My theory here is that you can actually revert working PS4 to any FW that it had in the past as long as there's a record for it in syscon.
For this to be performed, we need to initiate legitimate update process to lower FW (which is actually exists on debug units) and somehow forse it to rewrite backup slot with correct data from lower FW, then we just simply power off console, switch slots, cut syscon dump down to that FW version and perform normal reinstall on that lower firmware. 
This requires patched update.pup or qa flag or some debug/idu mode. Maybe you know it better from inside out.

**Comment by andy-man** [comment]
It's not so simple, my friend.
Every console has unique keys to encrypt/decrypt its fw. 
You can't share one fw between two consoles without encrypting. 

Yes testkit units has ability to install any FW but retail one does not have it.
Yes syscon has all previous signatures of all previously installed fws.

But you can't generate new coreOs without secret keys, which are unique to every console.
That mean that at present time we can't do downgrade, but only revert.
