### ISSUE TITLE
Can't this system be downgraded?

### ISSUE THREAD

**Issue by lazenes** [andy-man/ps4-wee-tools#30]
<img width="370" alt="image" src="https://github.com/andy-man/ps4-wee-tools/assets/18098025/0a56a189-ed6d-4077-aae4-4067aa562e4c">
I've obtained a dump of a NOR flash, and I'm not sure whether to call this a stupid downgrade or an upgrade. Could this information screen in the image contain a logical error? Should I proceed further and read the syscon chip as well, or should I not go any further? There's a risk of damaging the syscon chip when separating the D4 pin from the board, etc.

**Comment by andy-man** [comment]
This dump probably has overwritten CoreOS slot, revert is not possible
