### ISSUE TITLE
FW 11.50 Revert failed

### ISSUE THREAD

**Issue by k1netic88** [andy-man/ps4-wee-tools#31]
Ive launched 0.9.9 as a python script and have created nor switch patches that seem to build no problem.

While trying to create a syscon patch A, B or C I receive the following message

'not all arguments converted during string formatting'

it seems to be fine when comparing md5 with a syscon patch created with v0.9.5

I am trying to revert a console with 11.50 firmware which was updated directly from 9.00. The tool however reports the FW (active) is 1.62A and FW backup slot holds 10.50 <-> 11.50

 Ive tried all 14 switch patches and none have worked from either v0.9.5 or v0.9.9

edit - dumps attached

[ CUH-1002A B01.zip](https://github.com/andy-man/ps4-wee-tools/files/15280956/CUH-1002A.B01.zip)
[CUH-1002A B01.z01.zip](https://github.com/andy-man/ps4-wee-tools/files/15280957/CUH-1002A.B01.z01.zip)
[CUH-1002A B01.z02.zip](https://github.com/andy-man/ps4-wee-tools/files/15280958/CUH-1002A.B01.z02.zip)
[CUH-1002A B01.z03.zip](https://github.com/andy-man/ps4-wee-tools/files/15280959/CUH-1002A.B01.z03.zip)
[CUH-1002A B01.z04.zip](https://github.com/andy-man/ps4-wee-tools/files/15280960/CUH-1002A.B01.z04.zip)
[CUH-1002A B01.z05.zip](https://github.com/andy-man/ps4-wee-tools/files/15280961/CUH-1002A.B01.z05.zip)

remove .zip extension from z0x files, thanks github

**Comment by andy-man** [comment]
Thanks for feedback - all bugs are fixed in v1.0.0

Have you tried "legitimate" sflash patch?

What does uart report?

- Save all logs for each slot_switch patch
- Upload to gdrive 
- Post link here or better message me via [twitter](https://twitter.com/AndyManDev)

**Comment by k1netic88** [comment]
All nor patches have the same uart log

secure loader build: Mar  4 2024 05:19:13 (r10725:release_branches/release_11.500) [711MHz]
           AGESA: ThebePBDK       W5C21
                                             ERROR: main(3738) checkUpdVersion 0xffffffff != 0x11508000

after patching the syscon it will boot as normal.

with a legitimate patch the same occurs, I've tried fully reinstalling the 11.50 with a recovery image and with an update image through safe mode.

https://drive.google.com/drive/folders/1ET1dra6bNhAWDykzjaId3WMESpQWsnPl?usp=sharing

**Comment by andy-man** [comment]
There is the same FW in both slots
