### ISSUE TITLE
11.52 to 9.00 revert fail

### ISSUE THREAD

**Issue by TheKingdom009** [andy-man/ps4-wee-tools#38]
Hi Andy I'm trying to revert from 11.52 to 9.00 but I have failed. I tried all the slot switch bin files but it has failed

**Comment by andy-man** [comment]
Use legit patch

**Comment by truevapor** [comment]
@andy-man Hey, Andy. Could you please tell me about the “legith patch” method ? As I understand it, it is used to update the OS version in slots but not to downgrade the version. I'm trying to do a downgrade too and I'm having a problem: when I go into recovery mode (where you have to plug in the gamepad) I've never been able to get the version below 11.50 (which is currently installed).

**Comment by andy-man** [comment]
Legit patch serves to get working slot switch pattern. 
Read initial dump then update FW (recovery or from XMB it doesn't matter) and take second. 
Now you have 2 patterns for slot A and slot B. 
You can use it in future in any time cuz it will remain the same.

So after you've made those 2 dumps you can drop them on wee tools and it will create legit patch for dump1.
Remember if your initial dump has same FW in both slots revert is useless (I suppose that's your case).
