### ISSUE TITLE
Turn off FSM

### ISSUE THREAD

**Issue by Intruder911** [andy-man/ps4-wee-tools#39]
Hi, I have PS4 1000 model in FSM. Is there is any way to out from FSM? It was on very old 3.50FW, but with error su-39176-6 error on installation. So i reverted it by your tools to previous 2.02FW and had success FW re-installation. But as i said it is on factory / service mode. I think it was gone on factory/service mode in authorised service center Sony. Because there is no sign of soldering and UART was activated. No signs of soldering on UART pins and other pins. The PS4 and motherboard is as just from factory.
I tried change on your tool in "additional tools" section "boot mode", but it returns to main menu. On your old version 0.9.5 i can see only 2 records but they are same and i'm still in FSM.

Can you help me please? Thanks

**Comment by andy-man** [comment]
You need to use Syscon Rebuilder
It's feature of PS4 weeTools PRO

**Comment by Intruder911** [comment]
> 0.9.5 is very outdated version but even the lastest SE version doesn't handle cache items. You need to use Syscon Rebuilder (feature of PS4 weeTools PRO) to escape from FSM. PRO version can fix SU-39176-6, CE-40947-4 and other errors.

Just buyed. It's very very cheap - thanks for this separetly. didn't know there was a pro version of your tool. I'll try this version too. Thank you very much.
