### ISSUE TITLE
Validate the entirety of sflash0s0 (Except for NVS) with these md5s

### ISSUE THREAD

**Issue by zecoxao** [andy-man/ps4-wee-tools#4]
We can validate for the entirety of sflash0s0 (Except for 1.01, 3.70 and 5.07, and except for NVS) with these md5s

[md5.txt](https://github.com/andy-man/ps4-wee-tools/files/12054011/md5.txt)

**Comment by zecoxao** [comment]
This means that the first 2 MiB of sflash can effectively be fully validated when it comes to the BLS2 segments.

**Comment by zecoxao** [comment]
Here are the codenames i've got so far:

Aeolia A2 (0x0D, 0x0E)
Belize B0 (0x20, 0x21)
Baikal B1 (0x24, 0x25)
Belize 2 A0 (0x2A, 0x2B)

**Comment by andy-man** [comment]
thanks, that's cool - I'll add seg 0 validation. 
About codenames (values in brakets) what is the offset for it?

**Comment by zecoxao** [comment]
emc ipl is always first value, it's at 0x4000 size 0x60000 and after that again repeated with size 0x60000 at 0x64000
eap kbl is second value at 0xC4000 size 0x80000. 
i'm still checking the torus values (they're after that and the size is 0x80000 as well) because some of them aren't just one revision

**Comment by zecoxao** [comment]
for example

Aeolia A2 (0x0D, 0x0E) -> 0x0D is emc ipl for Aeolia A2, 0x0E is eap kbl for Aeolia A2

**Comment by Al-Azif** [comment]
[md5.txt](https://github.com/andy-man/ps4-wee-tools/files/12062932/md5.txt)
[2bls.txt](https://github.com/andy-man/ps4-wee-tools/files/12062933/2bls.txt)

Updated list and sqlite template for easy searching/matching

**Comment by andy-man** [comment]
added in [v0.7.4](https://github.com/andy-man/ps4-wee-tools/commit/b87f03ec5ef2aace961773bd551db90c620e7fda)

**Comment by ivanro1** [comment]
> added in v0.7.4

You can add to your program the way to fix the blue light errors for eapkey not aviable

**Comment by andy-man** [comment]
It is not right topic for hdd eap keys

* eap_hdd_key is stored in NVS partition at offset 0x1C9200 
* Size varies 0x40/0x60
* backup copy at (0x1CC200) (0x1C9200 + 0x3000)=>(0x1CC200) \*
* can be replaced with values of other dump (same mobo + same fw) \*

\*  not sure

**Comment by zecoxao** [comment]
thanks! i'll test it shortly :)

**Comment by zecoxao** [comment]
you could make a range for the md5s, since i'm aware that it doesn't always belong to the same version, for example 5.00, 5.01, 5.03, 5.05 or just 5.00 <-> 5.05
