### ISSUE TITLE
corrupted ps4 pro syscon

### ISSUE THREAD

**Issue by shoyrock** [andy-man/ps4-wee-tools#40]
Hey, I’m wondering if anyone here can help me. I made a backup of my Syscon and, before attempting to revert my PS4, I did this sometime last year. That’s not important, though. My Syscon chip has since died, so I got a new chip and tried to restore the backup to it. However, I was unable to boot the system—there’s no sound, no power, nothing. I’ve tried using some of the options in PS4 Wee Tools Pro to see if I can recover from the corrupted dumps, but I haven’t had any luck. Does anyone know how I might resolve this issue?

I tried uploading a backup of my NOR, but it’s too big. Let me know if it’s needed for you to help.

[God of war ps4 pro.zip](https://github.com/user-attachments/files/17036464/God.of.war.ps4.pro.zip)

**Comment by andy-man** [comment]
All your dumps has different MD5 hash - that is bad

1 Always read syscon for several times - until you get at least 2 equal dumps
2 Make sure that syscon FW's md5 hash is OK too (your dumps has probably corrupted FW)

![image](https://github.com/user-attachments/assets/4dd4e86d-abba-4a78-b4ef-f04c3e58a7bf)
FW and  SNVS/NVS areas has differences

You can try to use weeTools PRO to recover FW
6: Additional tools -> 5: Recover Syscon's FW
Expert mode? y
 0: fws\syscon\2.23_1.bin | 99.99%
 1: fws\syscon\2.23_2.bin | 99.98%
 
 Try 0 and 1 for each of your dumps (I suppose **Full Syscon FW Dump 03.bin** is best)

**Comment by shoyrock** [comment]
"I've gone over all the Syscon dumps with Remover 0 and 1, but there's still no sign of life. I'm not sure what other options I have left. Are there any tools or scripts that I can use to consolidate all three dumps into one working version?"

**Comment by andy-man** [comment]
Probably you have other HW problem(s)
"no sound, no power, nothing" - seems like bad sflash ic soldering and not syscon

Check PSU, mobo for shorts and standby voltages
Also check soldering of NOR and Syscon add more tin

You should see something like this in UART log (even with not-native syscon dump)
```
secure loader build: Apr 5 2021 05:20:19 (r10392:release_branches/release_08.500) [711MHz]
AGESA: ThebePBDK W5C21
```

**Comment by shoyrock** [comment]
I’m not sure how to go about testing for a short I’m new to all of this. This is the setup that I'm using now 
![IMG_1471](https://github.com/user-attachments/assets/92239379-4f3b-4cf7-b453-78ca439a80e4)

I tried testing for connectivity to see if I could find any problems. I discovered that I’m unable to get connectivity on pin 6 on the nor chip, which may be the problem or one of the problems. I am not sure how to go about fixing the problem. Could I bridge the connection, or could the connectivity problem come somewhere else? I tested the connectivity on another PS4, and it works fine. X marks the location where I’m unable to get a connection
![IMG_1472](https://github.com/user-attachments/assets/f2d2d68e-942a-4081-8a4e-95aeb6b058f2)

**Comment by shoyrock** [comment]
Side question: is there a diagram showing how to read and write to the syscon using tool, reset, and GND? I don't know if GND is needed, but that’s what I’ve used in the past, but I’m unable to do so using the teensy ++ 2.0. I don’t know if I’m doing something wrong

**Comment by andy-man** [comment]
Fix all HW problems first
Replace broken resistor, check NOR wiring again. 
Also I see that your syscon has broken pin... ergh I hope it works

Sorry, I don't provide general HW repair tips here

You can find all diagrams in assets folder of weeTools
https://github.com/andy-man/ps4-wee-tools/blob/master/assets/hw/syscon_flasher/diagram.jpg

**Comment by shoyrock** [comment]
There is no diagram for the three-wire r/w. And yeah, it seems to be a hardware problem, and yes, the system is working. I tested it on another PS4 and replaced it because I found an intermittent short that goes away when I remove the chip, but even replacing the system chip doesn’t fix a problem, so I guess I have to keep looking. Do you know where I can find a schematic for the PS4? I think I may need to replace some caps and resistors

**Comment by andy-man** [comment]
> There is no diagram for the three-wire r/w
Diagram is the same.

If your syscon is already in DEBUG mode you don't need connect glitch pin (VDD)
If you power it with standby of PS4 psu - no need to connect 5V (EVDD)

So you can only use 3 wires (if you met all conditions mentioned above)

(TOOL0) - rx/tx
(RESET) - reset
(VSS) - gnd

**Comment by Intruder911** [comment]
> I made a backup of my Syscon and, before attempting to revert my PS4,

For interest i downladed and checked your dumps - all of them are different. Just open two of them on HxD editor and press Ctrl+K you'll see

**Comment by shoyrock** [comment]
> > There is no diagram for the three-wire r/w
> 
> Diagram is the same.
> 
> If your syscon is already in DEBUG mode you don't need connect glitch pin (VDD) If you power it with standby of PS4 psu - no need to connect 5V (EVDD)
> 
> So you can only use 3 wires (if you met all conditions mentioned above)
> 
> (TOOL0) - rx/tx (RESET) - reset (VSS) - gnd

That's what I've been using. It works with another tool I'm using, but it doesn't work when using the teensy ++ 2 so I assumedi was doing something wrong . Also, do you know where I can find a board view for the PS4 pro

**Comment by shoyrock** [comment]
That sounds like my best option would be to buy a new motherboard. What I've been doing to try to read the syscon is on a working motherboard with debug enabled. I tried tried the points next to the UART TX. Hopefully, you can spot what I’m doing wrong
![IMG_1475](https://github.com/user-attachments/assets/8cc5444a-7a15-4f82-823a-53c236788d60)

**Comment by shoyrock** [comment]
I found the problem: syscon_flasher_v2.02_teensy2.0 is broken. It downgraded the chip to version 01.01, which is not compatible with ps4-wee-tools that require v2.02. I tested both PS4SysconTools_v2.0.2beta and PS4SysconTools_v2.1.0beta, and both versions contain the broken PS4SysconFlasher_Teensy++_2.0_v2.02.
