### ISSUE TITLE
Payment for pro versions in Russia, via Yandex.

### ISSUE THREAD

**Issue by AEZAKMI9432** [andy-man/ps4-wee-tools#44]
Hi, is it possible for you to add the issue of pro versions of the program when purchasing through Yandex?  If I indicate my email in the comments, can you send me the version of the program?

**Comment by andy-man** [comment]
Use Boosty - it does work in Russia. Each post contains most updated app.
Choose "Unlock post" to open access to updates without time restrictions.
Keep in mind - if you choose "subscription" you will lose access as soon as subscription is over.

Contact me at [4PDA](https://4pda.to/forum/index.php?act=qms&mid=1765649) if you need further assistance.

You can report issues in this repo (regardless Pro/SE version you use).

**Comment by AEZAKMI9432** [comment]
I paid the donation on Boosty but I didn't choose the product I needed. You can check your donations at Boosty ,and issue a utility for Ps4, pro version

**Comment by andy-man** [comment]
Check private messages on boosty
