### ISSUE TITLE
Virus Wacatac.H!ml detected

### ISSUE THREAD

**Issue by yuyubades** [andy-man/ps4-wee-tools#5]
Virus Wacatac.H!ml detected on last ver

**Comment by Al-Azif** [comment]
https://github.com/pyinstaller/pyinstaller/issues/5854

Just use the python script itself vs the packed exe if you're worried about it.

**Comment by andy-man** [comment]
That is just drawbacks of pyinstaller + MS Defender, there are no viruses. And as was mentioned above, if you don't trust exe you can always use original uncompiled py scripts.
