### ISSUE TITLE
Why my syscon is not  Patchable

### ISSUE THREAD

**Issue by LordRafa** [andy-man/ps4-wee-tools#7]
Hello,

I have made a dump of my syscon with the syscon tools but when I try to patch it to revert my ps4 firmware it says that it is not patcheable, any clue why is this happening?

**Comment by andy-man** [comment]
If tool says "not patchable" it means that your console already downloaded new FW but not installed it yet. In this case you can not revert FW because your CoreOS backup slot was overwritten with FW update.
If you want more detailed answer, provide your syscon dump

**Comment by rawadeldo** [comment]
thank you so much for your reply, actually I am curious because I didn't connect the ps4 for a while (more or less since I update the ps4) and I would say that I should be in 9.03 and prev was 9.0.0.

I would be really thankful if you want to investigate more. How can I send you the dump?

**Comment by LordRafa** [comment]
hanks for your reply. Now, I am curious because I didn't connect the PS4 to the electricity since I updated to 9.03 from 9.00.

I would be more than glad to provide you with my PS4 Syscon dump if you want to do some research. How can I send it to you?

**Comment by andy-man** [comment]
Just upload it to cloud and send link here or dm me on twitter
